def ability_from_params(params: list[str]) -> tuple[
        tuple[int, str], list[int], list[float], tuple[int, str], list[int], list[float], tuple[int, str], list[
            list[str]], int]: ...
